export const initialCards = [
  {
    "movieId": 1,
    "nameRU": "«Роллинг Стоунз 1»",
    "nameEN": "Stones",
    "director": "Testinka",
    "country": "США",
    "year": "2010",
    "duration": 61,
    "description": "В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена.",
    "trailerLink": "https://www.youtube.com/watch?v=D5fBhbEJxEU",
    "image": "https://api.nomoreparties.co/uploads/small_stones_in_exile_b2f1b8f4b7.jpeg",
    "thumbnail": "https://www.youtube.com"
  },
  {
    "movieId": 2,
    "nameRU": "«Роллинг Стоунз 2»",
    "nameEN": "Stones",
    "director": "Testinka",
    "country": "США",
    "year": "2010",
    "duration": 121,
    "description": "В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена.",
    "trailerLink": "https://www.youtube.com/watch?v=D5fBhbEJxEU",
    "image": "https://api.nomoreparties.co/uploads/small_stones_in_exile_b2f1b8f4b7.jpeg",
    "thumbnail": "https://www.youtube.com"
  },
  {
    "movieId": 3,
    "nameRU": "«Роллинг Стоунз 3»",
    "nameEN": "Stones",
    "director": "Testinka",
    "country": "США",
    "year": "2010",
    "duration": 80,
    "description": "В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена.",
    "trailerLink": "https://www.youtube.com/watch?v=D5fBhbEJxEU",
    "image": "https://api.nomoreparties.co/uploads/small_stones_in_exile_b2f1b8f4b7.jpeg",
    "thumbnail": "https://www.youtube.com"
  },
  {
    "movieId": 4,
    "nameRU": "«Роллинг Стоунз 4»",
    "nameEN": "Stones",
    "director": "Testinka",
    "country": "США",
    "year": "2010",
    "duration": 56,
    "description": "В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена.",
    "trailerLink": "https://www.youtube.com/watch?v=D5fBhbEJxEU",
    "image": "https://api.nomoreparties.co/uploads/small_stones_in_exile_b2f1b8f4b7.jpeg",
    "thumbnail": "https://www.youtube.com"
  },
  {
    "movieId": 5,
    "nameRU": "«Роллинг Стоунз 5»",
    "nameEN": "Stones",
    "director": "Testinka",
    "country": "США",
    "year": "2010",
    "duration": 123,
    "description": "В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена.",
    "trailerLink": "https://www.youtube.com/watch?v=D5fBhbEJxEU",
    "image": "https://api.nomoreparties.co/uploads/small_stones_in_exile_b2f1b8f4b7.jpeg",
    "thumbnail": "https://www.youtube.com"
  },
  {
    "movieId": 6,
    "nameRU": "«Роллинг Стоунз 6»",
    "nameEN": "Stones",
    "director": "Testinka",
    "country": "США",
    "year": "2010",
    "duration": 78,
    "description": "В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена.",
    "trailerLink": "https://www.youtube.com/watch?v=D5fBhbEJxEU",
    "image": "https://api.nomoreparties.co/uploads/small_stones_in_exile_b2f1b8f4b7.jpeg",
    "thumbnail": "https://www.youtube.com"
  },
  {
    "movieId": 7,
    "nameRU": "«Роллинг Стоунз 1»",
    "nameEN": "Stones",
    "director": "Testinka",
    "country": "США",
    "year": "2010",
    "duration": 111,
    "description": "В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена.",
    "trailerLink": "https://www.youtube.com/watch?v=D5fBhbEJxEU",
    "image": "https://api.nomoreparties.co/uploads/small_stones_in_exile_b2f1b8f4b7.jpeg",
    "thumbnail": "https://www.youtube.com"
  },
  {
    "movieId": 8,
    "nameRU": "«Роллинг Стоунз 2»",
    "nameEN": "Stones",
    "director": "Testinka",
    "country": "США",
    "year": "2010",
    "duration": 156,
    "description": "В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена.",
    "trailerLink": "https://www.youtube.com/watch?v=D5fBhbEJxEU",
    "image": "https://api.nomoreparties.co/uploads/small_stones_in_exile_b2f1b8f4b7.jpeg",
    "thumbnail": "https://www.youtube.com"
  },
  {
    "movieId": 9,
    "nameRU": "«Роллинг Стоунз 3»",
    "nameEN": "Stones",
    "director": "Testinka",
    "country": "США",
    "year": "2010",
    "duration": 39,
    "description": "В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена.",
    "trailerLink": "https://www.youtube.com/watch?v=D5fBhbEJxEU",
    "image": "https://api.nomoreparties.co/uploads/small_stones_in_exile_b2f1b8f4b7.jpeg",
    "thumbnail": "https://www.youtube.com"
  },
  {
    "movieId": 10,
    "nameRU": "«Роллинг Стоунз 4»",
    "nameEN": "Stones",
    "director": "Testinka",
    "country": "США",
    "year": "2010",
    "duration": 141,
    "description": "В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена.",
    "trailerLink": "https://www.youtube.com/watch?v=D5fBhbEJxEU",
    "image": "https://api.nomoreparties.co/uploads/small_stones_in_exile_b2f1b8f4b7.jpeg",
    "thumbnail": "https://www.youtube.com"
  },
  {
    "movieId": 11,
    "nameRU": "«Роллинг Стоунз 5»",
    "nameEN": "Stones",
    "director": "Testinka",
    "country": "США",
    "year": "2010",
    "duration": 145,
    "description": "В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена.",
    "trailerLink": "https://www.youtube.com/watch?v=D5fBhbEJxEU",
    "image": "https://api.nomoreparties.co/uploads/small_stones_in_exile_b2f1b8f4b7.jpeg",
    "thumbnail": "https://www.youtube.com"
  },
  {
    "movieId": 12,
    "nameRU": "«Роллинг Стоунз 6»",
    "nameEN": "Stones",
    "director": "Testinka",
    "country": "США",
    "year": "2010",
    "duration": 98,
    "description": "В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена.",
    "trailerLink": "https://www.youtube.com/watch?v=D5fBhbEJxEU",
    "image": "https://api.nomoreparties.co/uploads/small_stones_in_exile_b2f1b8f4b7.jpeg",
    "thumbnail": "https://www.youtube.com"
  }
];